### ISSUE TITLE
TypeError: The Study object must be a list

### ISSUE THREAD

**Issue by GuopingYe** [swhume/odmlib_examples#1]
I'm testing this tool for my curiosity, when I'm running the provided code in example xlsx2define2-1.py, it comes to an error "TypeError: The Study object must be a list" even I'm using the template xlsx file, seems it's from "odm_elem.create_define_objects", I'm not familiar with odmlib, could you please have a look? thank you!

**Comment by swhume** [comment]
Thanks for your question. I have been using xlsx2define2-1.py for a couple studies so there have been some minor updates. I updated the Define-XML models to support a single Study which is different from the ODM case where you can have multiple studies (a list). The version of odmlib you installed from PyPI still had the older model with Study as a list and that's why you experienced the TypeError. I've updated odmlib in PyPI to version 0.1.4, so please update your version of odmlib. I've also pushed the latest xlsx2define2-1.py so you may want to pull a new version of that as well.

I'm happy to help get you started, so let me know if you have other questions.

**Comment by GuopingYe** [comment]
> 

Thank you Sam! It works now, I have a further question, I found that xml created from the example code had no part of external "xsl" style sheet specified, I'm wondering in which tool you open these xml file?

**Comment by swhume** [comment]
Timely question. Modern browsers won't apply the stylesheet to a local define-xml file. IE11 was the last browser to do so and end-of-life is coming for it this June. So, I've been getting this question quite a bit. I've drafted a blog post with an open-source solution to generating the HTML file using the define2-1 style sheet. It's only draft at this point (use the link below), but should answer your question. Let me know if you have questions or see something I can improve.
https://swhume.github.io/blog-2022-generate-html-from-xml.html
